# Generated by Django 3.1.1 on 2020-09-20 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LinkChange',
            new_name='LinkDetail',
        ),
    ]
