# Generated by Django 3.1.1 on 2020-09-20 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0002_auto_20200921_0036'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkdetail',
            name='lazy',
            field=models.BooleanField(default=False),
        ),
    ]
