# Generated by Django 3.1.1 on 2020-09-21 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0003_linkdetail_lazy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkdetail',
            name='lazy',
            field=models.IntegerField(default=0),
        ),
    ]
